import { db, perguntasTable } from "@workspace/db";

const PILARES = [
  {
    slug: "estrategia",
    nome: "Estratégia e Governança",
    ordem: 1,
    questions: [
      { texto: "A clínica possui missão, visão e valores formalmente definidos e comunicados à equipe?", tipo: "sim_nao", peso: "1.00", ordem: 1, dica: "Verifique se há documento escrito ou apresentação que os colaboradores conhecem." },
      { texto: "Existe um planejamento estratégico anual com metas mensuráveis (KPIs)?", tipo: "sim_nao", peso: "1.00", ordem: 2, dica: "Exemplos de KPIs: taxa de ocupação, faturamento mensal, NPS, ticket médio." },
      { texto: "As metas estratégicas são revisadas com que frequência?", tipo: "texto_livre", peso: "0.80", ordem: 3, dica: "Periodicidade ideal: mensal ou trimestral." },
      { texto: "Qual é o nível de envolvimento dos sócios na gestão operacional do dia a dia?", tipo: "escala_1_5", peso: "1.00", ordem: 4, dica: "1 = Totalmente ausente, 5 = Muito envolvido e presente." },
      { texto: "Existe separação clara entre a pessoa jurídica da clínica e as finanças pessoais dos sócios?", tipo: "sim_nao", peso: "1.00", ordem: 5, dica: "Pró-labore definido? Contas bancárias separadas?" },
      { texto: "A clínica tem um organograma atualizado e conhecido por toda a equipe?", tipo: "sim_nao", peso: "0.80", ordem: 6, dica: "Hierarquia clara reduz conflitos e duplicidade de responsabilidades." },
      { texto: "Há reuniões de gestão periódicas com pauta e ata?", tipo: "sim_nao", peso: "0.80", ordem: 7, dica: "Reuniões semanais ou mensais com registro facilitam a accountability." },
      { texto: "A tomada de decisão é centralizada nos sócios ou distribuída para gestores?", tipo: "texto_livre", peso: "0.80", ordem: 8, dica: "Descreva o modelo atual de governança e tomada de decisão." },
      { texto: "Existe um comitê ou responsável dedicado à gestão (gestor/diretor clínico)?", tipo: "sim_nao", peso: "1.00", ordem: 9, dica: "A ausência de um gestor profissionalizado é um fator de risco comum." },
      { texto: "A clínica realiza análise SWOT ou análise de mercado periodicamente?", tipo: "sim_nao", peso: "0.80", ordem: 10, dica: "Análise competitiva e de mercado é fundamental para posicionamento estratégico." },
      { texto: "Os profissionais de saúde conhecem e compartilham da visão de crescimento da clínica?", tipo: "sim_nao", peso: "0.80", ordem: 11, dica: "Alinhamento da equipe clínica com os objetivos estratégicos." },
      { texto: "Existem indicadores definidos para monitorar a saúde do negócio mensalmente?", tipo: "sim_nao", peso: "1.00", ordem: 12, dica: "Exemplos: faturamento, inadimplência, produtividade por profissional, etc." },
      { texto: "Como você avalia o processo de tomada de decisão estratégica na clínica?", tipo: "escala_1_5", peso: "1.00", ordem: 13, dica: "1 = Muito desestruturado e reativo, 5 = Estruturado, baseado em dados." },
      { texto: "A clínica tem plano de contingência para cenários de crise (perda de profissional-chave, queda de receita)?", tipo: "sim_nao", peso: "1.00", ordem: 14, dica: "Planos de contingência aumentam a resiliência do negócio." },
      { texto: "A liderança da clínica tem clareza sobre as forças e fraquezas do negócio?", tipo: "escala_1_5", peso: "1.00", ordem: 15, dica: "1 = Baixa clareza, 5 = Alta clareza e ação sobre os pontos de melhoria." },
      { texto: "Existe acordo entre sócios formalizado sobre papéis, responsabilidades e retiradas?", tipo: "sim_nao", peso: "1.00", ordem: 16, dica: "Acordo de sócios previne conflitos e define regras de saída." },
      { texto: "A clínica realiza benchmarking com concorrentes ou referências de mercado?", tipo: "sim_nao", peso: "0.80", ordem: 17, dica: "Benchmarking ajuda a identificar oportunidades e diferenciais competitivos." },
      { texto: "Como você avalia a maturidade de gestão estratégica da clínica?", tipo: "escala_1_5", peso: "1.20", ordem: 18, dica: "1 = Muito imaturo/informal, 5 = Altamente estruturado e profissionalizado." },
    ],
  },
  {
    slug: "financeiro",
    nome: "Financeiro e Fluxo de Caixa",
    ordem: 2,
    questions: [
      { texto: "A clínica realiza controle de fluxo de caixa diário ou semanal?", tipo: "sim_nao", peso: "1.00", ordem: 1, dica: "Controle frequente evita surpresas e permite tomada de decisão ágil." },
      { texto: "Qual é o prazo médio de recebimento das consultas/procedimentos (particular, planos, convênios)?", tipo: "texto_livre", peso: "0.80", ordem: 2, dica: "Descreva o prazo médio por modalidade de recebimento." },
      { texto: "A clínica conhece sua margem de contribuição por procedimento?", tipo: "sim_nao", peso: "1.00", ordem: 3, dica: "Margem de contribuição = Receita – Custos Variáveis diretos." },
      { texto: "Existe reserva de capital de giro equivalente a pelo menos 3 meses de despesas fixas?", tipo: "sim_nao", peso: "1.00", ordem: 4, dica: "Reserva mínima recomendada para segurança operacional." },
      { texto: "Como você avalia a previsibilidade da receita mensal da clínica?", tipo: "escala_1_5", peso: "1.00", ordem: 5, dica: "1 = Muito imprevisível, 5 = Altamente previsível e recorrente." },
      { texto: "A clínica monitora a taxa de inadimplência e possui processo de cobrança estruturado?", tipo: "sim_nao", peso: "1.00", ordem: 6, dica: "Taxa de inadimplência saudável varia por segmento, mas idealmente abaixo de 3%." },
      { texto: "O DRE (Demonstrativo de Resultados) é elaborado mensalmente?", tipo: "sim_nao", peso: "1.00", ordem: 7, dica: "DRE mensal permite identificar lucro/prejuízo e tendências financeiras." },
      { texto: "A clínica tem acesso a crédito ou linhas de financiamento para expansão, se necessário?", tipo: "sim_nao", peso: "0.80", ordem: 8, dica: "Relação bancária saudável e histórico positivo facilitam acesso a crédito." },
      { texto: "Qual é o percentual de receita proveniente de planos de saúde/convênios?", tipo: "numerico", peso: "1.00", ordem: 9, dica: "Informe o percentual aproximado em %. Alta concentração em convênios é fator de risco.", valorMin: "0.00", valorMax: "100.00", inverso: false },
      { texto: "A clínica realiza análise de rentabilidade por especialidade ou profissional?", tipo: "sim_nao", peso: "1.00", ordem: 10, dica: "Identificar procedimentos e profissionais mais rentáveis otimiza a alocação de recursos." },
      { texto: "As despesas fixas e variáveis estão claramente categorizadas e controladas?", tipo: "sim_nao", peso: "1.00", ordem: 11, dica: "Categorização permite identificar oportunidades de redução de custos." },
      { texto: "A clínica possui meta de faturamento definida por mês?", tipo: "sim_nao", peso: "1.00", ordem: 12, dica: "Meta de faturamento deve ser baseada em capacidade instalada e histórico." },
      { texto: "Como você avalia a saúde financeira atual da clínica?", tipo: "escala_1_5", peso: "1.20", ordem: 13, dica: "1 = Em situação crítica/déficit, 5 = Excelente/lucrativa com reservas." },
      { texto: "Existe separação clara entre os pagamentos de sócios (pró-labore/dividendos) e os custos operacionais?", tipo: "sim_nao", peso: "1.00", ordem: 14, dica: "Misturar finanças pessoais com empresariais distorce os resultados reais da clínica." },
      { texto: "A clínica investe em precificação estratégica de seus serviços?", tipo: "sim_nao", peso: "1.00", ordem: 15, dica: "Precificação baseada em custos + margem desejada + posicionamento de mercado." },
      { texto: "Qual é o ticket médio por consulta/procedimento?", tipo: "numerico", peso: "0.80", ordem: 16, dica: "Informe o valor médio em reais (R$) por atendimento particular.", valorMin: "0.00", valorMax: "500.00", inverso: false },
      { texto: "A clínica acompanha o ponto de equilíbrio (break-even) mensalmente?", tipo: "sim_nao", peso: "1.00", ordem: 17, dica: "Ponto de equilíbrio = quando a receita cobre todos os custos fixos e variáveis." },
      { texto: "Existem processos para controle e aprovação de despesas acima de determinado valor?", tipo: "sim_nao", peso: "0.80", ordem: 18, dica: "Alçadas de aprovação evitam gastos não planejados e aumentam o controle." },
      { texto: "Como você avalia a maturidade de gestão financeira da clínica?", tipo: "escala_1_5", peso: "1.20", ordem: 19, dica: "1 = Sem controle ou gestão, 5 = Altamente estruturado com relatórios e previsões." },
      { texto: "A clínica possui política de concessão de descontos com critérios e alçadas definidas?", tipo: "sim_nao", peso: "0.80", ordem: 20, dica: "Descontos sem política clara comprometem a margem e criam percepção de valor inconsistente." },
      { texto: "Existe acompanhamento do ROI de investimentos realizados (equipamentos, reformas, treinamentos)?", tipo: "sim_nao", peso: "1.00", ordem: 21, dica: "Calcular o retorno sobre investimentos ajuda a priorizar alocações futuras de capital." },
    ],
  },
  {
    slug: "contabil",
    nome: "Contabilidade e Fiscal",
    ordem: 3,
    questions: [
      { texto: "A clínica possui contabilidade regular com escritório contábil ou contador interno?", tipo: "sim_nao", peso: "1.00", ordem: 1, dica: "Contabilidade regular é obrigação legal e fonte de informação de gestão." },
      { texto: "Qual é o regime tributário atual da clínica?", tipo: "texto_livre", peso: "0.80", ordem: 2, dica: "Simples Nacional, Lucro Presumido ou Lucro Real? O regime é revisado anualmente?" },
      { texto: "A clínica está em dia com todas as obrigações acessórias (SPED, e-Social, DCTF, etc.)?", tipo: "sim_nao", peso: "1.00", ordem: 3, dica: "Obrigações acessórias em atraso geram multas e problemas com o Fisco." },
      { texto: "O contador fornece relatórios gerenciais além da contabilidade fiscal obrigatória?", tipo: "sim_nao", peso: "0.80", ordem: 4, dica: "Relatórios gerenciais complementam a tomada de decisão estratégica." },
      { texto: "A clínica realiza planejamento tributário para otimizar a carga fiscal?", tipo: "sim_nao", peso: "1.00", ordem: 5, dica: "Planejamento tributário legal pode reduzir significativamente impostos pagos." },
      { texto: "Há controle adequado de notas fiscais emitidas e recebidas?", tipo: "sim_nao", peso: "1.00", ordem: 6, dica: "Controle de NFs é obrigação fiscal e facilita a reconciliação contábil." },
      { texto: "A clínica tem parcelamentos ou débitos em aberto com a Receita Federal ou prefeitura?", tipo: "sim_nao", peso: "1.00", ordem: 7, dica: "Débitos tributários comprometem a capacidade de crédito e geram juros." },
      { texto: "Os sócios recebem pró-labore e/ou distribuição de lucros de forma documentada?", tipo: "sim_nao", peso: "1.00", ordem: 8, dica: "Formalizar remuneração dos sócios protege juridicamente a empresa." },
      { texto: "Como você avalia a organização contábil e fiscal da clínica?", tipo: "escala_1_5", peso: "1.20", ordem: 9, dica: "1 = Desorganizada e em atraso, 5 = Totalmente regular e planejada." },
      { texto: "A clínica realiza inventário e controle de ativos (equipamentos, imóveis)?", tipo: "sim_nao", peso: "0.80", ordem: 10, dica: "Controle de ativos é necessário para depreciação contábil e seguros adequados." },
      { texto: "O ISS (Imposto sobre Serviços) é recolhido corretamente de acordo com o município?", tipo: "sim_nao", peso: "1.00", ordem: 11, dica: "Alíquota e obrigações de ISS variam por município. Verifique a legislação local." },
      { texto: "A clínica mantém documentos contábeis arquivados pelo prazo legal (mínimo 5 anos)?", tipo: "sim_nao", peso: "0.80", ordem: 12, dica: "Guarda de documentos fiscais é obrigação legal e proteção em caso de auditoria." },
      { texto: "Há planejamento para sucessão ou venda eventual da clínica?", tipo: "sim_nao", peso: "0.80", ordem: 13, dica: "Planejamento patrimonial e successório evita problemas fiscais no futuro." },
      { texto: "A clínica avalia periodicamente se o regime tributário atual é o mais vantajoso?", tipo: "sim_nao", peso: "1.00", ordem: 14, dica: "Com o crescimento da receita, o regime ideal pode mudar. Revisão anual é recomendada." },
      { texto: "Como você avalia o relacionamento da clínica com o escritório contábil?", tipo: "escala_1_5", peso: "1.00", ordem: 15, dica: "1 = Relacionamento precário/sem suporte, 5 = Parceria estratégica e proativa." },
      { texto: "A clínica possui seguro empresarial (responsabilidade civil, equipamentos, estabelecimento)?", tipo: "sim_nao", peso: "0.80", ordem: 16, dica: "Seguros protegem contra sinistros que podem comprometer a continuidade do negócio." },
      { texto: "Existe controle de contas a pagar e a receber integrado à contabilidade?", tipo: "sim_nao", peso: "1.00", ordem: 17, dica: "Integração financeira-contábil garante consistência dos números e facilita auditorias." },
      { texto: "Os médicos/dentistas prestam serviços como PJ (pessoa jurídica)? Os contratos estão formalizados?", tipo: "sim_nao", peso: "1.00", ordem: 18, dica: "Contratos PJ sem formalização adequada geram risco trabalhista (pejotização irregular)." },
    ],
  },
  {
    slug: "marketing",
    nome: "Vendas, Marketing e Captação de Pacientes",
    ordem: 4,
    questions: [
      { texto: "A clínica possui uma estratégia de marketing digital estruturada?", tipo: "sim_nao", peso: "1.00", ordem: 1, dica: "Inclui: redes sociais, Google Meu Negócio, site, anúncios pagos, SEO." },
      { texto: "Como os novos pacientes chegam à clínica? Qual canal é o principal?", tipo: "texto_livre", peso: "0.80", ordem: 2, dica: "Descreva os principais canais: indicação, Google, Instagram, convênio, localização, etc." },
      { texto: "A clínica monitora a taxa de conversão de consultas iniciais em tratamentos?", tipo: "sim_nao", peso: "1.00", ordem: 3, dica: "Taxa de conversão = % de pacientes novos que iniciam tratamento após primeira consulta." },
      { texto: "Existe um processo estruturado de retorno e retenção de pacientes?", tipo: "sim_nao", peso: "1.00", ordem: 4, dica: "Lembretes de retorno, follow-up pós-consulta, programa de fidelidade." },
      { texto: "A clínica tem presença ativa e consistente nas redes sociais?", tipo: "sim_nao", peso: "0.80", ordem: 5, dica: "Frequência mínima recomendada: 3-4 publicações por semana com conteúdo relevante." },
      { texto: "Como você avalia a reputação online da clínica (Google, Doctoralia, Reclame Aqui)?", tipo: "escala_1_5", peso: "1.00", ordem: 6, dica: "1 = Muitas avaliações negativas ou ausência de avaliações, 5 = Excelente reputação." },
      { texto: "Qual é a nota média da clínica no Google Meu Negócio?", tipo: "numerico", peso: "0.80", ordem: 7, dica: "Informe a nota de 1 a 5. Nota acima de 4,5 é considerada ótima.", valorMin: "1.00", valorMax: "5.00", inverso: false },
      { texto: "A clínica investe em tráfego pago (Google Ads, Meta Ads)?", tipo: "sim_nao", peso: "0.80", ordem: 8, dica: "Investimento em mídia paga deve ser monitorado pelo CAC (Custo de Aquisição de Cliente)." },
      { texto: "O site da clínica é otimizado para buscas locais e mobile?", tipo: "sim_nao", peso: "0.80", ordem: 9, dica: "Site responsivo, rápido, com informações de contato e agendamento online." },
      { texto: "A clínica mede o Custo de Aquisição de Paciente (CAP)?", tipo: "sim_nao", peso: "1.00", ordem: 10, dica: "CAP = Total investido em marketing / Número de novos pacientes adquiridos." },
      { texto: "Existe um processo de coleta de avaliações/depoimentos de pacientes satisfeitos?", tipo: "sim_nao", peso: "0.80", ordem: 11, dica: "Depoimentos autênticos aumentam a credibilidade e auxiliam na decisão de novos pacientes." },
      { texto: "A clínica realiza ações de marketing de conteúdo (blog, vídeos educativos)?", tipo: "sim_nao", peso: "0.80", ordem: 12, dica: "Conteúdo educativo posiciona a clínica como autoridade e atrai tráfego orgânico." },
      { texto: "Como você avalia a identidade visual e o posicionamento de marca da clínica?", tipo: "escala_1_5", peso: "1.00", ordem: 13, dica: "1 = Sem identidade clara, 5 = Marca forte, diferenciada e reconhecida." },
      { texto: "A clínica oferece facilidades de agendamento online (WhatsApp, site, app)?", tipo: "sim_nao", peso: "1.00", ordem: 14, dica: "Agendamento digital reduz barreiras e aumenta a taxa de conversão de interessados." },
      { texto: "A clínica tem programa de indicação (referral) para pacientes e parceiros?", tipo: "sim_nao", peso: "0.80", ordem: 15, dica: "Programas de indicação bem estruturados são um dos canais de maior ROI." },
      { texto: "Existe acompanhamento de métricas de marketing (alcance, engajamento, leads gerados)?", tipo: "sim_nao", peso: "1.00", ordem: 16, dica: "Métricas de marketing permitem otimização contínua das estratégias adotadas." },
      { texto: "A clínica possui proposta de valor clara e diferenciada em relação aos concorrentes?", tipo: "texto_livre", peso: "1.00", ordem: 17, dica: "Qual é o diferencial competitivo da clínica? Por que um paciente escolheria vocês?" },
      { texto: "Como você avalia a maturidade de marketing e captação de pacientes da clínica?", tipo: "escala_1_5", peso: "1.20", ordem: 18, dica: "1 = Sem estratégia, depende apenas de indicações espontâneas, 5 = Marketing estruturado e multicanal." },
    ],
  },
  {
    slug: "operacoes",
    nome: "Processos Operacionais e Atendimento",
    ordem: 5,
    questions: [
      { texto: "A clínica possui fluxograma documentado do processo de atendimento ao paciente?", tipo: "sim_nao", peso: "1.00", ordem: 1, dica: "Da chegada ao pós-atendimento: recepção, anamnese, consulta, pagamento, retorno." },
      { texto: "Como você avalia a eficiência do processo de agendamento e controle de agenda?", tipo: "escala_1_5", peso: "1.00", ordem: 2, dica: "1 = Muitos conflitos e falhas, 5 = Altamente eficiente com baixa taxa de no-show." },
      { texto: "Qual é a taxa de não comparecimento (no-show) sem aviso prévio?", tipo: "numerico", peso: "1.00", ordem: 3, dica: "Informe o percentual estimado (%). Taxa acima de 10% requer intervenção ativa.", valorMin: "0.00", valorMax: "100.00", inverso: true },
      { texto: "Existe protocolo para o tratamento de reclamações e insatisfações de pacientes?", tipo: "sim_nao", peso: "1.00", ordem: 4, dica: "Protocolo de atendimento a reclamações é obrigatório para ISO e melhores práticas." },
      { texto: "A clínica mede periodicamente a satisfação dos pacientes (NPS, pesquisa pós-consulta)?", tipo: "sim_nao", peso: "1.00", ordem: 5, dica: "NPS (Net Promoter Score) mede a probabilidade de indicação e lealdade dos pacientes." },
      { texto: "Os processos de esterilização e biossegurança estão documentados e são seguidos?", tipo: "sim_nao", peso: "1.00", ordem: 6, dica: "Obrigação legal e de segurança do paciente. Documentação é exigida em fiscalizações." },
      { texto: "Existe padronização no atendimento telefônico e na recepção da clínica?", tipo: "sim_nao", peso: "0.80", ordem: 7, dica: "Script de atendimento e treinamento da equipe de front-desk são fundamentais." },
      { texto: "A clínica possui controle de estoque de materiais e insumos com ponto de reposição definido?", tipo: "sim_nao", peso: "0.80", ordem: 8, dica: "Falta de insumos gera cancelamentos e impacta a experiência do paciente." },
      { texto: "Como você avalia a experiência do paciente na clínica (ambiente, tempo de espera, atendimento)?", tipo: "escala_1_5", peso: "1.00", ordem: 9, dica: "1 = Experiência ruim com reclamações frequentes, 5 = Experiência excelente e elogiada." },
      { texto: "A clínica possui indicadores de produtividade por consultório/cadeira e por profissional?", tipo: "sim_nao", peso: "1.00", ordem: 10, dica: "Taxa de ocupação ideal: acima de 75% da capacidade instalada." },
      { texto: "Os processos de faturamento com convênios estão padronizados e com baixa taxa de glosa?", tipo: "sim_nao", peso: "1.00", ordem: 11, dica: "Glosas acima de 5% indicam necessidade de revisão dos processos de faturamento." },
      { texto: "Existe manual de procedimentos operacionais (MOP) ou procedimentos operacionais padrão (POPs)?", tipo: "sim_nao", peso: "0.80", ordem: 12, dica: "POPs garantem consistência e facilitam o treinamento de novos colaboradores." },
      { texto: "A limpeza e organização das instalações são realizadas seguindo protocolos definidos?", tipo: "sim_nao", peso: "0.80", ordem: 13, dica: "Checklist de limpeza e manutenção é fundamental para biossegurança e fiscalizações." },
      { texto: "Como você avalia a capacidade de escala operacional da clínica (horários, profissionais, espaço)?", tipo: "escala_1_5", peso: "1.00", ordem: 14, dica: "1 = Totalmente saturada sem capacidade de crescimento, 5 = Com ampla capacidade para crescer." },
      { texto: "Existe processo de acompanhamento pós-tratamento com o paciente?", tipo: "sim_nao", peso: "0.80", ordem: 15, dica: "Follow-up pós-consulta aumenta satisfação, fidelização e taxa de indicação." },
      { texto: "A clínica registra e analisa os motivos de cancelamento e não retorno de pacientes?", tipo: "sim_nao", peso: "1.00", ordem: 16, dica: "Análise de cancelamentos e churn é fundamental para melhoria contínua." },
      { texto: "Como você avalia a maturidade dos processos operacionais da clínica?", tipo: "escala_1_5", peso: "1.20", ordem: 17, dica: "1 = Processos informais e dependentes de pessoas-chave, 5 = Processos documentados e escaláveis." },
      { texto: "A clínica realiza manutenção preventiva dos equipamentos com registro?", tipo: "sim_nao", peso: "0.80", ordem: 18, dica: "Manutenção preventiva evita paradas inesperadas e prolonga a vida útil dos equipamentos." },
      { texto: "A clínica monitora o tempo médio de espera do paciente desde a chegada até o atendimento?", tipo: "sim_nao", peso: "0.80", ordem: 19, dica: "Tempo de espera acima de 20 minutos afeta a satisfação e a fidelização do paciente." },
      { texto: "Como você avalia a eficiência no processo de check-in e check-out do paciente?", tipo: "escala_1_5", peso: "1.00", ordem: 20, dica: "1 = Processo lento e cheio de falhas, 5 = Processo ágil, digital e sem filas." },
      { texto: "A clínica possui protocolo de atendimento de emergência e primeiros socorros?", tipo: "sim_nao", peso: "1.00", ordem: 21, dica: "Protocolo de emergência e equipe treinada em primeiros socorros são requisitos de segurança." },
    ],
  },
  {
    slug: "pessoas",
    nome: "Gestão de Pessoas e Cultura",
    ordem: 6,
    questions: [
      { texto: "A clínica possui processo estruturado de recrutamento e seleção?", tipo: "sim_nao", peso: "1.00", ordem: 1, dica: "Processo seletivo com critérios claros reduz rotatividade e melhora a qualidade das contratações." },
      { texto: "Existe plano de cargos, salários e benefícios formalmente definido?", tipo: "sim_nao", peso: "1.00", ordem: 2, dica: "Plano de cargos e salários aumenta a transparência e reduz conflitos salariais." },
      { texto: "Como você avalia o nível de engajamento e motivação da equipe?", tipo: "escala_1_5", peso: "1.00", ordem: 3, dica: "1 = Equipe desmotivada com alta rotatividade, 5 = Equipe altamente engajada e comprometida." },
      { texto: "A taxa de rotatividade (turnover) de colaboradores está sob controle?", tipo: "sim_nao", peso: "1.00", ordem: 4, dica: "Turnover acima de 20% ao ano indica problemas de gestão de pessoas." },
      { texto: "A clínica realiza avaliações de desempenho periódicas com feedback estruturado?", tipo: "sim_nao", peso: "1.00", ordem: 5, dica: "Avaliações semestrais ou anuais com critérios claros e feedback construtivo." },
      { texto: "Existe programa de treinamento e capacitação contínua para a equipe?", tipo: "sim_nao", peso: "1.00", ordem: 6, dica: "Treinamentos técnicos e comportamentais melhoram qualidade e engajamento." },
      { texto: "A clínica está em conformidade com a legislação trabalhista (CLT, e-Social)?", tipo: "sim_nao", peso: "1.00", ordem: 7, dica: "Irregularidades trabalhistas geram passivos significativos em auditorias." },
      { texto: "Existe cultura de feedback contínuo e comunicação transparente entre liderança e equipe?", tipo: "sim_nao", peso: "0.80", ordem: 8, dica: "Comunicação aberta e regular reduz conflitos e aumenta o alinhamento estratégico." },
      { texto: "Como você avalia o clima organizacional da clínica?", tipo: "escala_1_5", peso: "1.00", ordem: 9, dica: "1 = Clima ruim com muitos conflitos, 5 = Clima excelente com alto nível de satisfação." },
      { texto: "Os colaboradores conhecem claramente suas atribuições e responsabilidades?", tipo: "sim_nao", peso: "0.80", ordem: 10, dica: "Descrição de cargos clara reduz sobreposição de funções e aumenta produtividade." },
      { texto: "A clínica tem programa de reconhecimento e recompensa por resultados?", tipo: "sim_nao", peso: "0.80", ordem: 11, dica: "Reconhecimento não financeiro e financeiro aumenta motivação e retenção de talentos." },
      { texto: "Existe Comissão Interna de Prevenção de Acidentes (CIPA) ou PPRA conforme obrigação?", tipo: "sim_nao", peso: "0.80", ordem: 12, dica: "Dependendo do porte, CIPA e PPRA são obrigações legais. Verifique os requisitos." },
      { texto: "A liderança da clínica promove e exemplifica os valores da organização?", tipo: "escala_1_5", peso: "1.00", ordem: 13, dica: "1 = Liderança não exemplar, 5 = Liderança inspiradora e alinhada aos valores." },
      { texto: "Existe processo de onboarding estruturado para novos colaboradores?", tipo: "sim_nao", peso: "0.80", ordem: 14, dica: "Onboarding eficaz reduz o tempo de adaptação e aumenta a retenção nos primeiros 90 dias." },
      { texto: "A clínica realiza pesquisa de clima organizacional periodicamente?", tipo: "sim_nao", peso: "0.80", ordem: 15, dica: "Pesquisa de clima é ferramenta essencial para identificar insatisfações antes que virem problemas." },
      { texto: "Os contratos de trabalho (CLT) ou de prestação de serviços (PJ) estão regularizados?", tipo: "sim_nao", peso: "1.00", ordem: 16, dica: "Contratos irregulares geram risco trabalhista significativo em caso de rescisão ou fiscalização." },
      { texto: "Como você avalia a maturidade de gestão de pessoas da clínica?", tipo: "escala_1_5", peso: "1.20", ordem: 17, dica: "1 = Sem estrutura de RH, 5 = Gestão de pessoas profissionalizada e estratégica." },
      { texto: "A clínica investe no desenvolvimento pessoal e profissional de lideranças intermediárias?", tipo: "sim_nao", peso: "1.00", ordem: 18, dica: "Líderes de nível médio (coordenadores, supervisores) são fundamentais para escalar a operação." },
    ],
  },
  {
    slug: "tecnologia",
    nome: "Tecnologia e Sistemas",
    ordem: 7,
    questions: [
      { texto: "A clínica utiliza algum software de gestão (PMS/sistema clínico)?", tipo: "sim_nao", peso: "1.00", ordem: 1, dica: "Exemplos: Doctoralia, iClinic, MedSênior, Totvs, ClinicWeb, etc." },
      { texto: "Qual é o sistema de gestão utilizado e qual o nível de adoção pela equipe?", tipo: "texto_livre", peso: "0.80", ordem: 2, dica: "Descreva o sistema e o percentual de funcionalidades realmente utilizadas." },
      { texto: "Os prontuários médicos são 100% eletrônicos?", tipo: "sim_nao", peso: "1.00", ordem: 3, dica: "Prontuário eletrônico é obrigatório em muitas especialidades e facilita acesso à informação." },
      { texto: "Existe backup regular e seguro dos dados da clínica?", tipo: "sim_nao", peso: "1.00", ordem: 4, dica: "Backup diário automatizado em nuvem é o mínimo recomendado para continuidade de negócio." },
      { texto: "A clínica possui wifi separado para pacientes e para a rede interna?", tipo: "sim_nao", peso: "0.80", ordem: 5, dica: "Separação de redes é prática básica de cibersegurança." },
      { texto: "Qual é o nível de digitalização do processo de agendamento e confirmação de consultas?", tipo: "escala_1_5", peso: "1.00", ordem: 6, dica: "1 = Totalmente manual (agenda papel/ligações), 5 = 100% digital com confirmação automática." },
      { texto: "A clínica utiliza ferramentas de automação para comunicação com pacientes (WhatsApp, e-mail)?", tipo: "sim_nao", peso: "1.00", ordem: 7, dica: "Automação de confirmações e lembretes reduz no-show significativamente." },
      { texto: "A equipe recebe treinamento regular para uso adequado das ferramentas tecnológicas?", tipo: "sim_nao", peso: "0.80", ordem: 8, dica: "Treinamento em tecnologia aumenta a adoção e o retorno sobre o investimento em software." },
      { texto: "Existe política de segurança de senhas e controle de acessos ao sistema?", tipo: "sim_nao", peso: "1.00", ordem: 9, dica: "Controle de acesso por usuário individual é requisito de segurança e LGPD." },
      { texto: "A clínica utiliza telemedicina ou teleconsulta?", tipo: "sim_nao", peso: "0.80", ordem: 10, dica: "Telemedicina é regulamentada pelo CFM e pode expandir a capacidade de atendimento." },
      { texto: "Como você avalia a infraestrutura de TI da clínica (internet, computadores, equipamentos)?", tipo: "escala_1_5", peso: "1.00", ordem: 11, dica: "1 = Infraestrutura precária e obsoleta, 5 = Infraestrutura moderna e estável." },
      { texto: "A clínica utiliza dashboards ou relatórios digitais para acompanhar indicadores de desempenho?", tipo: "sim_nao", peso: "1.00", ordem: 12, dica: "Relatórios digitais eliminam planilhas manuais e agilizam a tomada de decisão baseada em dados." },
      { texto: "Existe integração entre os sistemas utilizados (gestão + financeiro + agenda)?", tipo: "sim_nao", peso: "1.00", ordem: 13, dica: "Integração elimina retrabalho e reduz erros de digitação entre sistemas." },
      { texto: "A clínica possui contrato de suporte técnico para os sistemas críticos?", tipo: "sim_nao", peso: "0.80", ordem: 14, dica: "Suporte técnico contratado garante resposta rápida em casos de falha de sistemas críticos." },
      { texto: "Como você avalia a maturidade tecnológica da clínica?", tipo: "escala_1_5", peso: "1.20", ordem: 15, dica: "1 = Muito analógica e dependente de processos manuais, 5 = Altamente digital e automatizada." },
      { texto: "A clínica realiza análise de dados para tomada de decisão (relatórios de produção, faturamento)?", tipo: "sim_nao", peso: "1.00", ordem: 16, dica: "Análise de dados clínicos e financeiros é diferencial competitivo crescente na saúde." },
      { texto: "Existe plano de contingência para indisponibilidade dos sistemas?", tipo: "sim_nao", peso: "0.80", ordem: 17, dica: "O que acontece se o sistema cair? Existe processo manual de emergência documentado?" },
      { texto: "A clínica utiliza assinatura digital para documentos (contratos, consentimentos)?", tipo: "sim_nao", peso: "0.80", ordem: 18, dica: "Assinatura digital é legalmente válida e agiliza processos administrativos." },
    ],
  },
  {
    slug: "compliance",
    nome: "Conformidade, Regulamentação e LGPD",
    ordem: 8,
    questions: [
      { texto: "A clínica está registrada e em situação regular no conselho de classe correspondente (CFM, CRO, CRN, etc.)?", tipo: "sim_nao", peso: "1.00", ordem: 1, dica: "Regularidade no conselho de classe é requisito básico para funcionamento legal." },
      { texto: "O alvará de funcionamento da clínica está válido e atualizado?", tipo: "sim_nao", peso: "1.00", ordem: 2, dica: "Alvará vencido implica em interdição imediata pela vigilância sanitária." },
      { texto: "A clínica possui licença sanitária da VISA (Vigilância Sanitária) válida?", tipo: "sim_nao", peso: "1.00", ordem: 3, dica: "Licença sanitária é obrigatória para estabelecimentos de saúde em todos os municípios." },
      { texto: "Os equipamentos de saúde (radiologia, lasers, etc.) possuem registro e calibração atualizados?", tipo: "sim_nao", peso: "1.00", ordem: 4, dica: "Equipamentos médicos exigem registro na ANVISA e manutenção periódica documentada." },
      { texto: "A clínica tem Responsável Técnico (RT) formalmente designado e registrado?", tipo: "sim_nao", peso: "1.00", ordem: 5, dica: "RT é obrigação legal para estabelecimentos de saúde. Deve constar no alvará." },
      { texto: "Existe programa de gerenciamento de resíduos de saúde (PGRSS) implementado?", tipo: "sim_nao", peso: "1.00", ordem: 6, dica: "PGRSS é obrigatório para clínicas que geram resíduos de saúde (RSS). Fiscalizado pela VISA." },
      { texto: "A clínica possui Programa de Prevenção de Riscos Ambientais (PPRA/PGR) atualizado?", tipo: "sim_nao", peso: "0.80", ordem: 7, dica: "PGR (substitui PPRA) é obrigatório para empresas com funcionários CLT." },
      { texto: "A clínica já foi submetida a alguma auditoria ou fiscalização nos últimos 2 anos?", tipo: "sim_nao", peso: "0.80", ordem: 8, dica: "Se sim, foram identificadas não-conformidades? Foram corrigidas? Documente." },
      { texto: "Existe política de privacidade e termos de uso alinhados com a LGPD?", tipo: "sim_nao", peso: "1.00", ordem: 9, dica: "LGPD (Lei 13.709/2018) é obrigatória para todas as empresas que tratam dados pessoais." },
      { texto: "A clínica possui Encarregado de Dados (DPO) designado, mesmo que informal?", tipo: "sim_nao", peso: "0.80", ordem: 10, dica: "DPO é recomendado para clínicas. Para grandes volumes de dados sensíveis, pode ser obrigatório." },
      { texto: "Existe termo de consentimento livre e esclarecido (TCLE) para todos os procedimentos?", tipo: "sim_nao", peso: "1.00", ordem: 11, dica: "TCLE protege a clínica juridicamente e é obrigatório para procedimentos de risco." },
      { texto: "A clínica possui seguro de responsabilidade civil profissional (malpractice)?", tipo: "sim_nao", peso: "0.80", ordem: 12, dica: "Seguro de responsabilidade civil é fortemente recomendado para todos os profissionais de saúde." },
      { texto: "Como você avalia a conformidade da clínica com a LGPD?", tipo: "escala_1_5", peso: "1.20", ordem: 13, dica: "1 = Sem nenhuma adequação, 5 = Totalmente adequada com DPO, políticas e treinamentos." },
      { texto: "Os contratos com pacientes, fornecedores e prestadores são revisados periodicamente por advogado?", tipo: "sim_nao", peso: "0.80", ordem: 14, dica: "Revisão jurídica periódica protege a clínica de passivos contratuais não percebidos." },
      { texto: "A equipe recebe treinamentos sobre boas práticas de segurança do paciente?", tipo: "sim_nao", peso: "1.00", ordem: 15, dica: "Cultura de segurança do paciente reduz eventos adversos e responsabilidade legal." },
      { texto: "A clínica possui câmeras de segurança e política de retenção das imagens?", tipo: "sim_nao", peso: "0.80", ordem: 16, dica: "Política de câmeras deve ser comunicada a pacientes e colaboradores (LGPD)." },
      { texto: "Existe protocolo documentado para notificação de eventos adversos e queixas técnicas?", tipo: "sim_nao", peso: "1.00", ordem: 17, dica: "Notificação de eventos adversos é obrigação legal (NOTIVISA/ANVISA) em muitos casos." },
      { texto: "Como você avalia a maturidade de conformidade e regulamentação da clínica?", tipo: "escala_1_5", peso: "1.20", ordem: 18, dica: "1 = Em situação irregular com múltiplas não-conformidades, 5 = Totalmente regular e auditável." },
    ],
  },
];

async function main() {
  console.log("Checking if perguntas already seeded...");
  const existing = await db.select().from(perguntasTable);
  if (existing.length > 0) {
    console.log(`Already seeded: ${existing.length} questions found. Skipping.`);
    process.exit(0);
  }

  console.log("Seeding perguntas from CSV data (150 questions across 8 pillars)...");
  const allQuestions = PILARES.flatMap((pilar) =>
    pilar.questions.map((q) => ({
      pilarSlug: pilar.slug,
      pilarNome: pilar.nome,
      pilarOrdem: pilar.ordem,
      texto: q.texto,
      tipo: q.tipo,
      peso: q.peso,
      ordem: q.ordem,
      dica: q.dica ?? null,
      valorMin: (q as { valorMin?: string }).valorMin ?? null,
      valorMax: (q as { valorMax?: string }).valorMax ?? null,
      inverso: (q as { inverso?: boolean }).inverso ?? false,
    }))
  );

  await db.insert(perguntasTable).values(allQuestions);
  console.log(`Seeded ${allQuestions.length} questions successfully.`);
  process.exit(0);
}

main().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
