import { Router, type IRouter } from "express";
import { requireSuperAdmin } from "../middleware/auth";
import healthRouter from "./health";
import storageRouter from "./storage";
import authRouter from "./auth";
import clinicsRouter from "./clinics";
import dashboardRouter from "./dashboard";
import activityRouter from "./activity";
import kickoffsRouter from "./kickoffs";
import diagnosticsRouter from "./diagnostics";
import perguntasRouter from "./perguntas";
import aiRouter from "./ai";
import actionsRouter from "./actions";
import risksRouter from "./risks";
import teamRouter from "./team";
import faturasRouter from "./faturas";
import notificationsRouter from "./notifications";
import statusHistoryRouter from "./status-history";
import sociosRouter from "./socios";
import perfilOperacionalRouter from "./perfil-operacional";
import parceirosExternosRouter from "./parceiros-externos";
import sistemasUsoRouter from "./sistemas-uso";
import docsConstitutivoRouter from "./docs-constitutivos";
import lgpdTermosRouter from "./lgpd-termos";
import { autentiquePublicRouter, autentiqueProtectedRouter } from "./autentique";
import delegacoesRouter from "./delegacoes";
import processosRouter from "./processos";
import evidenciasRouter from "./evidencias";
import documentosRouter from "./documentos";
import jobsRouter from "./jobs";
import notificationPreferencesRouter from "./notification-preferences";
import pushRouter from "./push";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use(authRouter);
router.use(requireSuperAdmin, dashboardRouter);
router.use(requireSuperAdmin, clinicsRouter);
router.use(requireSuperAdmin, statusHistoryRouter);
router.use(requireSuperAdmin, sociosRouter);
router.use(requireSuperAdmin, activityRouter);
router.use(requireSuperAdmin, kickoffsRouter);
router.use(requireSuperAdmin, diagnosticsRouter);
router.use(requireSuperAdmin, perguntasRouter);
router.use(requireSuperAdmin, aiRouter);
router.use(requireSuperAdmin, actionsRouter);
router.use(requireSuperAdmin, risksRouter);
router.use(requireSuperAdmin, teamRouter);
router.use(requireSuperAdmin, faturasRouter);
router.use(requireSuperAdmin, perfilOperacionalRouter);
router.use(requireSuperAdmin, parceirosExternosRouter);
router.use(requireSuperAdmin, sistemasUsoRouter);
router.use(requireSuperAdmin, docsConstitutivoRouter);
router.use(requireSuperAdmin, lgpdTermosRouter);
router.use(requireSuperAdmin, autentiqueProtectedRouter);
router.use(requireSuperAdmin, delegacoesRouter);
router.use(requireSuperAdmin, processosRouter);
router.use(requireSuperAdmin, evidenciasRouter);
router.use(requireSuperAdmin, documentosRouter);
router.use(autentiquePublicRouter);
router.use(notificationsRouter);
router.use(requireSuperAdmin, jobsRouter);
router.use(notificationPreferencesRouter);
router.use(pushRouter);

export default router;
