// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/societary-docs-redesign/VariantB.tsx": () => import("../components/mockups/societary-docs-redesign/VariantB.tsx")
};
