// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/societary-docs-redesign/VariantB.tsx": () => import("../components/mockups/societary-docs-redesign/VariantB.tsx"),
  "./components/mockups/painel-clinica/HubDeModulos.tsx": () => import("../components/mockups/painel-clinica/HubDeModulos.tsx"),
  "./components/mockups/painel-clinica/TopoSegmentado.tsx": () => import("../components/mockups/painel-clinica/TopoSegmentado.tsx"),
  "./components/mockups/painel-clinica/TrilhoDuplo.tsx": () => import("../components/mockups/painel-clinica/TrilhoDuplo.tsx")
};
